[build]
  command = "python -m uvicorn run:app --host 0.0.0.0 --port 8000"
  publish = "public"

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/fastapi_function"
  status = 200
